module DownloadStatus {
  enum {
    OK = 0,
    INSUFFICIENT_SUBSCRIPTION_CAPABILITIES = 1,
    EXTERNAL_SCHEDULE = 2,
    NO_WORKOUT_AVAILABLE = 3,
    NO_WORKOUT = 4,
    DEVICE_DOES_NOT_SUPPORT_DOWNLOAD = 5,
    NO_FIT_DATA_RETURNED = 6,
    WORKOUT_NOT_DOWNLOAD_CAPABLE = 7
  }
}
