(:glance)
module DownloadStatus {
  enum {
    OK = 0,
    INSUFFICIENT_SUBSCRIPTION_CAPABILITIES = 1,
    DEVICE_DOES_NOT_SUPPORT_DOWNLOAD = 2,
    EXTERNAL_SCHEDULE = 3,
    NO_WORKOUT_AVAILABLE = 4,
    WORKOUT_NOT_DOWNLOAD_CAPABLE = 5,
    RESPONSE_MISSING_WORKOUT_DATA = 6,
    RESPONSE_CODE_ZERO = 7,
    NOT_YET_ATTEMPTED = 8
  }
}
