module TaoConstants {
  enum {
    DOWNLOAD_RESULT_OK = 0,
    DOWNLOAD_RESULT_INSUFFICIENT_SUBSCRIPTION_CAPABILITIES = 1,
    DOWNLOAD_RESULT_EXTERNAL_SCHEDULE = 2,
    DOWNLOAD_RESULT_NO_WORKOUT_AVAILABLE = 3,
    DOWNLOAD_RESULT_NO_WORKOUT = 4,
    DOWNLOAD_RESULT_UNSUPPORTED = 5,
    DOWNLOAD_RESULT_NO_FIT_DATA_LOADED = 6,
    DOWNLOAD_RESULT_NOT_DOWNLOAD_CAPABLE = 7
  }
}
