module TaoConstants {
  enum {
    DOWNLOAD_RESULT_OK = 0,
    DOWNLOAD_RESULT_INSUFFICIENT_SUBSCRIPTION_CAPABILITIES = 1,
    DOWNLOAD_RESULT_NO_WORKOUT = 2,
    DOWNLOAD_RESULT_UNSUPPORTED = 3,
    DOWNLOAD_RESULT_NO_FIT_DATA_LOADED = 4
  }
}
